### ISSUE TITLE
Create Router for RPC requests

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/ethereum_rust#15]
Ideally we would have a RPC router similar to the one describen in this video

https://www.youtube.com/watch?v=Gc5Nj5LJe1U

We should be able to do something like
```
   RpcRouter::new()
      .add("engine_exchangeCapabilities", engine::exchange_capabilities)
```

Ideally it would pass the rpc `params` field into the appropriate types to pass to the router function.

**Comment by lferrigno** [comment]
Blocked:

We need to define exactly which crate to use

**Comment by mpaulucci** [comment]
Closing for now, since it's low priority
