### ISSUE TITLE
Check best way to calculate state_root and storage_root

### ISSUE THREAD

**Issue by ElFantasma** [lambdaclass/ethereum_rust#203]
We are currently building transient Merkle Patricia Trees to [compute genesis block state root](https://github.com/lambdaclass/ethereum_rust/blob/99193bf5b17b50dfae4d3b549a67091a0c8a9bcf/crates/core/types/account.rs#L112) and [storage root for each account](https://github.com/lambdaclass/ethereum_rust/blob/99193bf5b17b50dfae4d3b549a67091a0c8a9bcf/crates/core/types/account.rs#L112). 

Check if we should sort the (key, value) tuples instead and use [compute_hash_from_sorted_iter](https://github.com/lambdaclass/merkle_patricia_tree/blob/2c30f64287ece5156560ee864a0f1f14e2b4bfab/src/lib.rs#L206) which would calculate the tree root without generating the full tree

**Comment by fmoletta** [comment]
Solved by #410 & #407
