### ISSUE TITLE
Check if genesis block is already in the database before inserting it.

### ISSUE THREAD

**Issue by ElFantasma** [lambdaclass/ethereum_rust#204]
We should [check if storage already contains a genesis block](https://github.com/lambdaclass/ethereum_rust/blob/99193bf5b17b50dfae4d3b549a67091a0c8a9bcf/crates/storage/storage.rs#L396), and compare it's hash with the one retrieved from the genesis.json to decide if we should create a new one, update current, or leave it untouched.

**Comment by varun-doshi** [comment]
Is this still open?
