### ISSUE TITLE
Add support for validating legacy transactions

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/ethereum_rust#23]
https://docs.infura.io/api/networks/ethereum/concepts/transaction-types

> Transactions with type 0x0 are legacy transactions that use the transaction format existing before typed transactions were introduced in [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718). They contain the parameters nonce, gasPrice, gasLimit, to, value, data, v, r, and s. Legacy transactions don’t use [access lists](https://docs.infura.io/api/networks/ethereum/concepts/transaction-types#access-list-transactions) or incorporate [EIP-1559 fee market changes](https://docs.infura.io/api/networks/ethereum/concepts/transaction-types#undefined).

**Comment by fmoletta** [comment]
Closed by: #73 as evm already performs validations before executing
