### ISSUE TITLE
Reuse merkle trees in ef_tests

### ISSUE THREAD

**Issue by ElFantasma** [lambdaclass/ethereum_rust#243]
Currently we are calculating the state root recreating the merkle tree from scratch each time we require it. (ie. [here](https://github.com/lambdaclass/ethrex/blob/d2197aaa7ce4e8192253a349c181df55edda247b/cmd/ef_tests/test_runner.rs#L121) and [here](https://github.com/lambdaclass/ethrex/blob/d2197aaa7ce4e8192253a349c181df55edda247b/cmd/ef_tests/test_runner.rs#L186)).

We should keep the world state in memory and update only the state transitions.

Its a follow up on #45 and there is a TODO comment [in code](https://github.com/lambdaclass/ethrex/blob/d2197aaa7ce4e8192253a349c181df55edda247b/crates/storage/storage.rs#L401)

**Comment by mpaulucci** [comment]
I think this intermediate step is not needed, let's go directly for https://github.com/lambdaclass/ethereum_rust/issues/244
