### ISSUE TITLE
Implement Changesets

### ISSUE THREAD

**Issue by Arkenan** [lambdaclass/ethereum_rust#297]
To be able to simulate or perform reorgs, we need to be able to go from one state to the previous one until we reach a certain previous state, so we can then execute transactions in a different fork.

To be able to "go back in time" it would be useful to have reversible changesets between states. This would prevent the recalculation of every state transition from genesis to the connection point.

As a simple definition of done, this ticket can be marked as close if we can:

1. Calculate transition from state A to B. This should calculate a changeset.
2. Rollback from B to A using the calculated changeset.
3. The rolled back state should be equal to the original state before applying the state transition in 1.

This ticket may be further divided if it's dimmed too broad.

**Comment by mpaulucci** [comment]
We've pivoted to hash based tries, which can trivially handle reverts, so Im closing this for now.
