### ISSUE TITLE
Add simple "transaction mempool"

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/ethereum_rust#348]
We could start by creating a table in the db that stores pending transactions.

Something like `TransactionHash => Transaction` 

Once we see a transaction in a block, we should remove it from the pending transactions table. An additional complexity is that when there is a reorg we should add it back. 

Things that add to the tx pool:
- eth_sendTransaction requests
- eth_sendRawTransaction requests
- transactions coming from p2p.

**Comment by MrishoLukamba** [comment]
taking it

**Comment by mpaulucci** [comment]
Closed by #408
